name: Format

on:
  push:
    branches:
      - v2.1
      - v2
      - v1
  pull_request:
    branches:
      - v2.1
      - v2
      - v1

jobs:
  format:
    runs-on: macos-latest
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v6
      - name: Install rustfmt with stable toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - name: Check formatting
        run: cargo fmt --manifest-path=Cargo.toml --all -- --check
