name: Clippy
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - dev
env:
  RUSTFLAGS: "-Dwarnings"
jobs:
  clippy:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - name: install webkit2gtk
        run: |
          sudo apt-get update
          sudo apt-get install -y webkit2gtk-4.0
      - name: Install clippy with stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: clippy
      - name: Run Clippy
        run: cargo clippy --manifest-path=Cargo.toml --all-targets --all-features -- -D warnings
