name: Test

on:
  push:
    branches:
      - v2.1
      - v2
      - v1
  pull_request:
    branches:
      - v2.1
      - v2
      - v1
    paths-ignore:
      - "webview-src/**"
      - "webview-dist/**"
      - "examples/**"

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest]

    steps:
      - uses: actions/checkout@v6

      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable

      - uses: Swatinem/rust-cache@v2

      - name: Run tests
        run: cargo test --manifest-path=Cargo.toml --release --lib --bins

      - name: Run doctests
        env:
          RUSTDOCFLAGS: -D warnings
        run: cargo test --manifest-path=Cargo.toml --release --doc
